apiVersion: v1
kind: Service
metadata:
  name: my-gin-app-service
  labels:
    app: my-gin-app
spec:
  selector:
    app: my-gin-app
  ports:
    - protocol: TCP
      port: 9998  
      targetPort: 9999 
  type: LoadBalancer
